import type { Project, Slide } from '@/types'

const now = new Date('2026-08-08T12:00:00.000Z').toISOString()

const demoPhotoIds = ['demo-01', 'demo-02', 'demo-03', 'demo-04', 'demo-05', 'demo-06']

const demoSlides: Slide[] = [
  {
    id: 'slide-01',
    order: 0,
    photoId: demoPhotoIds[0],
    type: 'hook',
    headline: "Jamaica doesn't reveal itself from a car window.",
    body: 'Some routes only start making sense once the road ends and the walking begins.',
    altText: 'A coastal wetland scene in Hellshire with editorial text about seeing Jamaica on foot.',
    alignment: 'left',
    placement: 'bottom-left',
    overlay: 42,
    shadow: true,
    crop: 'center',
    confidence: 0.88,
    reasoningSummary: 'Text sits low-left because the crocodile and water fill the upper frame.',
    editedFields: [],
  },
  {
    id: 'slide-02',
    order: 1,
    photoId: demoPhotoIds[1],
    type: 'observation',
    headline: 'The trail introduced itself slowly.',
    body: 'A road, then mud, then mangroves. The hike kept changing before we did.',
    altText: 'Hikers walking down a route in Hellshire with a short narrative caption.',
    alignment: 'left',
    placement: 'top-left',
    overlay: 36,
    shadow: true,
    crop: 'center',
    confidence: 0.84,
    reasoningSummary: 'The sky leaves room for a short top-left block without crossing the hikers.',
    editedFields: [],
  },
  {
    id: 'slide-03',
    order: 2,
    photoId: demoPhotoIds[2],
    type: 'nature',
    headline: 'What looks quiet from far away is crowded up close.',
    body: 'Wetlands carry detail in layers: roots, water, birds, movement, patience.',
    altText: 'A wetland landscape with layered mangrove textures and overlay text.',
    alignment: 'center',
    placement: 'center',
    overlay: 32,
    shadow: true,
    crop: 'center',
    confidence: 0.82,
    reasoningSummary: 'Centered placement uses the negative space above the wetland line.',
    editedFields: [],
  },
  {
    id: 'slide-04',
    order: 3,
    photoId: demoPhotoIds[3],
    type: 'transition',
    headline: 'Then the coast widened the story.',
    body: 'The route stopped feeling enclosed and started speaking in horizon lines.',
    altText: 'Hellshire coastline with reflective editorial text over the image.',
    alignment: 'right',
    placement: 'top-right',
    overlay: 34,
    shadow: true,
    crop: 'center',
    confidence: 0.86,
    reasoningSummary: 'The sea keeps the right third visually calm enough for a tight caption block.',
    editedFields: [],
  },
  {
    id: 'slide-05',
    order: 4,
    photoId: demoPhotoIds[4],
    type: 'reflection',
    headline: 'Sometimes the pause is the point.',
    body: 'Not every hike asks for speed. Some ask whether you are paying attention yet.',
    altText: 'A reflective beach scene with a short thoughtful caption.',
    alignment: 'left',
    placement: 'bottom-left',
    overlay: 44,
    shadow: true,
    crop: 'center',
    confidence: 0.9,
    reasoningSummary: 'Bottom-left keeps the open coastline visible while anchoring the reflective line.',
    editedFields: [],
  },
  {
    id: 'slide-06',
    order: 5,
    photoId: demoPhotoIds[5],
    type: 'cta',
    headline: 'Walk with the people who keep showing up.',
    body: 'Lifestyle Hikers turns routes into stories, and stories into reasons to come back.',
    altText: 'A trail sign from Hellshire with a Lifestyle Hikers call to action.',
    alignment: 'left',
    placement: 'bottom-left',
    overlay: 48,
    shadow: true,
    crop: 'center',
    cta: 'Plan the next trail with @lifestylehikers',
    confidence: 0.93,
    reasoningSummary: 'The sign already behaves like a CTA anchor, so text stays low and direct.',
    editedFields: [],
  },
]

export const demoProject: Project = {
  id: 'demo-coastal-jamaica',
  title: 'Hellshire Coastal Story',
  location: 'Hellshire, St. Catherine',
  notes: 'Lifestyle Hikers moved through mangroves, wetlands, coast, and open beach terrain in Hellshire. The story should feel editorial, observant, and grounded in how the landscape kept changing from one section to the next.',
  createdAt: now,
  updatedAt: now,
  status: 'generated',
  coverPhotoId: demoPhotoIds[0],
  photos: [
    { id: demoPhotoIds[0], originalName: '01-cover.webp', url: '/demo/01-cover.webp', width: 1200, height: 1600, mimeType: 'image/webp' },
    { id: demoPhotoIds[1], originalName: '02-trail.webp', url: '/demo/02-trail.webp', width: 1200, height: 1600, mimeType: 'image/webp' },
    { id: demoPhotoIds[2], originalName: '03-wetlands.webp', url: '/demo/03-wetlands.webp', width: 1200, height: 1600, mimeType: 'image/webp' },
    { id: demoPhotoIds[3], originalName: '04-coast.webp', url: '/demo/04-coast.webp', width: 1200, height: 1600, mimeType: 'image/webp' },
    { id: demoPhotoIds[4], originalName: '05-reflection.webp', url: '/demo/05-reflection.webp', width: 1200, height: 1600, mimeType: 'image/webp' },
    { id: demoPhotoIds[5], originalName: '06-cta.webp', url: '/demo/06-cta.webp', width: 1200, height: 1600, mimeType: 'image/webp' },
  ],
  slides: demoSlides,
  caption: "Some places only become legible when you slow down long enough to walk them. Hellshire gave us wetlands, coastline, mud, patience, and a reminder that the transition is often the story. Lifestyle Hikers keeps making space for routes that are worth remembering. Plan the next trail with @lifestylehikers.",
  hashtags: ['#LifestyleHikers', '#JamaicaHiking', '#Hellshire', '#OutdoorStorytelling'],
  keywords: ['Hellshire', 'coastal hike', 'wetlands', 'Jamaica', 'editorial carousel'],
}
